kind: ReplicationController
apiVersion: v1
metadata:
  name: etcd-discovery
spec:
  replicas: 1
  selector:
    name: etcd-discovery
  template:
    metadata:
      labels:
        name: etcd-discovery
    spec:
      containers:
      - name: discovery
        image: openshift/etcd-20-centos7
        args:
        - etcd-discovery.sh
        ports:
        - containerPort: 2379
          protocol: TCP
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      serviceAccount: ''
