sudo: required
language: node_js
services:
- docker
- redis-server
node_js:
- 'node'
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
env:
  - PGVERSION=9.0
  - PGVERSION=9.1
  - PGVERSION=9.2
  - PGVERSION=9.3
  - PGVERSION=9.4
  - PGVERSION=9.5
install: true
notifications:
  email:
  - howardc93@gmail.com
  - christian@paral.in
  - aqc2109@columbia.edu
before_script:
#- sudo service postgresql stop
#- docker run --name postgres -v /var/lib/postgresql/data:/var/lib/postgresql/data --restart=always -u postgres --net=host postgres:9.5
#- docker run --name redis --restart=always --net=host redis:3
#- docker run --name cassandra --restart=always --net=host cassandra:latest
- docker pull yasp/yasp:latest && docker build -t "yasp/yasp:latest" .
script:
# run test outside container
#- npm run test && (npm run coveralls || true)
# run test inside container, don't need to build since the docker image already built
- docker run -e "TEST_SKIP_BUILD=y" -e "COVERALLS_SERVICE_NAME=travis-ci" -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN --net=host -i yasp/yasp:latest "npm run test && (npm run coveralls || true)"
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: cluster/scripts/deploy.sh
