language: generic
sudo: required
services:
- docker
addons:
  postgresql: "9.4"
notifications:
  email:
  - howardc93@gmail.com
  - christian@paral.in
  - aqc2109@columbia.edu
before_script:
- sudo add-apt-repository -y ppa:chris-lea/redis-server
- sudo apt-get update
- sudo apt-get install -y redis-server
- sudo service redis-server start
- sudo docker build -t "yasp/yasp:latest" .
script:
- sudo docker run -e "TEST_SKIP_BUILD=y" -e "TEST_INSTALL_GLOBAL=y" --privileged=true --net=host -i yasp/yasp:latest npm run test
after_success:
- sudo docker run -i --privileged=true --net=host yasp/yasp:latest npm run coveralls
before_deploy:
- sudo docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: k8s
  script: scripts/docker_hub_push.bash
