sudo: required
language: node_js
services:
- docker
node_js:
- 'node'
notifications:
  email:
  - howardc93@gmail.com
  - christian@paral.in
  - aqc2109@columbia.edu
before_install:
install: true
before_script:
- sudo service postgresql stop
- sudo docker run -d --privileged --name cassandra --net=host -e "CASSANDRA_LISTEN_ADDRESS=127.0.0.1" cassandra:3
- sudo docker run -d --privileged --name postgres --net=host postgres:9.5
- sudo docker run -d --privileged --name redis --net=host redis:3
- sudo docker build -t yasp/parser https://github.com/yasp-dota/parser.git
- sudo docker run -d --name parser --net=host yasp/parser
- sudo docker pull yasp/yasp && sudo docker build -t "yasp/yasp" .
script:
# run test outside container
#- npm run test && (npm run coveralls || true)
# run test inside container
- docker run -e "COVERALLS_SERVICE_NAME=travis-ci" -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN --net=host -i yasp/yasp sh -c 'npm run test && (npm run coveralls || true)'
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: scripts/postbuild.sh
