sudo: required
language: node_js
services:
- docker
- redis-server
node_js:
- '5.0'
addons:
  postgresql: "9.4"
install: true
notifications:
  email:
  - howardc93@gmail.com
  - christian@paral.in
  - aqc2109@columbia.edu
# This is an attempt to make caching work
before_script:
- docker pull yasp/yasp:latest
- docker build -t "yasp/yasp:latest" .
script:
# don't need to build since the docker image already built
- docker run -e "TEST_SKIP_BUILD=y" -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID --net=host -i yasp/yasp:latest npm run test
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: k8s
  script: cluster/scripts/deploy.bash
