language: generic
sudo: required
services:
- docker
- redis-server
addons:
  postgresql: "9.4"
deploy:
notifications:
  email:
  - howardc93@gmail.com
  - christian@paral.in
  - aqc2109@columbia.edu
before_script:
- docker build -t "yasp/yasp:latest" .
script:
- docker run -e "TEST_SKIP_BUILD=y" -e "TEST_INSTALL_GLOBAL=y" --net=host -i yasp/yasp:latest test/run.sh
after_success:
- docker run -i --net=host yasp/yasp:latest npm run coveralls
before_deploy:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: k8s
  script: scripts/docker_hub_push.bash
