sudo: required
language: node_js
services:
- docker
node_js:
- 'node'
notifications:
  email:
  - howardc93@gmail.com
  - christian@paral.in
  - aqc2109@columbia.edu
before_install:
install: true
before_script:
- sudo service postgresql stop
- docker run --privileged --name cassandra --net=host cassandra:3
- docker run --privileged --name postgres --net=host postgres:9.5
- docker run --privileged --name redis --net=host redis:3
- docker pull yasp/yasp:latest && docker build -t "yasp/yasp:latest" .
script:
# run test outside container
#- npm run test && (npm run coveralls || true)
# run test inside container, don't need to build since the docker image already built
- docker run -e "TEST_SKIP_BUILD=y" -e "COVERALLS_SERVICE_NAME=travis-ci" -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN --net=host -i yasp/yasp:latest sh -c 'npm run test && (npm run coveralls || true)'
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: scripts/postbuild.sh
