# Does not set up Cassandra

version: '2'
services:
  db:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    network_mode: host
  cache:
    image: redis:3
    network_mode: host
  web:
    build: .
    command: ./docker/main-launch.sh basic # change 'basic' to 'everything' to launch all services
    ports:
      - "5000"
    volumes:
      - .:/usr/src/yasp
    network_mode: host
    depends_on:
      - db
      - cache
