apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    app: postgres
    deploymentconfig: postgres
    tier: backend
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 2
      maxUnavailable: 1
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: postgres
        deploymentconfig: postgres
        tier: backend
    spec:
      volumes:
      - name: postgres
      containers:
      - args: [ "postgres" ]
        image: postgres/9
        imagePullPolicy: Always
        name: postgres
        ports:
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange