apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    app: redis
    deploymentconfig: redis
    tier: backend
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 2
      maxUnavailable: 1
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: redis
        deploymentconfig: redis
        tier: backend
    spec:
      volumes:
      - name: redis
        gcePersistentDisk:
        pdName: disk-redis
        fsType: ext4
      containers:
      - args: [ "redis-server /var/lib/redis/redis.conf" ]
        image: redis/3
        imagePullPolicy: Always
        name: redis
        ports:
        volumeMounts:
        - name: redis
          mountPath: /var/lib/redis
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  