apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: yasp-deploy
  name: yasp-deploy
spec:
  replicas: 1
  selector:
    app: yasp-deploy
    tier: infra
  template:
    metadata:
      labels:
        app: yasp-deploy
        tier: infra
    spec:
      containers:
      - name: deploy
        image: paralin/kubedeploy:0.0.3
        env:
        - name: KUBERNETES_NAMESPACE
          value: yasp
        - name: WEBHOOK_SECRET
          value: secret
        - name: REPLICATION_CONTROLLERS
          value: web, fullhistory, mmr, parser, scanner, skill, worker
        - name: DOCKER_IMAGE
          value: yasp/yasp
        - name: TRAVIS_REPOSITORY
          value: yasp-dota/yasp
        - name: DEPLOY_BRANCH
          value: k8s
        ports:
        - containerPort: 8080
          name: api
