apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    tier: backend
    deployment: yasp
  name: fullhistory-1
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: fullhistory
    tier: backend
  template:
    metadata:
      labels:
        app: fullhistory
        tier: backend
    spec:
      containers:
      - name: yasp
        image: yasp/yasp:8c3dece
        args: [ "node", "fullhistory.js" ]
        imagePullPolicy: Always
      restartPolicy: Always
----
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    tier: backend
    deployment: yasp
  name: mmr-1
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: mmr
    tier: backend
  template:
    metadata:
      labels:
        app: mmr
        tier: backend
    spec:
      containers:
      - name: yasp
        image: yasp/yasp:8c3dece
        args: [ "node", "mmr.js" ]
        imagePullPolicy: Always
      restartPolicy: Always
----
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    tier: backend
    deployment: yasp
  name: scanner-1
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: scanner
    tier: backend
  template:
    metadata:
      labels:
        app: scanner
        tier: backend
    spec:
      containers:
      - name: yasp
        image: yasp/yasp:8c3dece
        args: [ "node", "scanner.js" ]
        imagePullPolicy: Always
      restartPolicy: Always
----
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    tier: backend
    deployment: yasp
  name: skill-1
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: skill
    tier: backend
  template:
    metadata:
      labels:
        app: skill
        tier: backend
    spec:
      containers:
      - name: yasp
        image: yasp/yasp:8c3dece
        args: [ "node", "skill.js" ]
        imagePullPolicy: Always
      restartPolicy: Always
----
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    tier: backend
    deployment: yasp
  name: worker-1
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: worker
    tier: backend
  template:
    metadata:
      labels:
        app: worker
        tier: backend
    spec:
      containers:
      - name: yasp
        image: yasp/yasp:8c3dece
        args: [ "node", "worker.js" ]
        imagePullPolicy: Always
      restartPolicy: Always