apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    tier: backend
    deployment: yasp
  name: fullhistory-1
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: fullhistory
    tier: backend
  template:
    metadata:
      labels:
        app: fullhistory
        tier: backend
    spec:
      containers:
      - name: yasp
        image: yasp/yasp:8c3dece
        args: [ "node", "fullhistory.js" ]
        imagePullPolicy: Always
      restartPolicy: Always