apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    tier: backend
    deployment: mmr
  name: mmr-1
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: mmr
    tier: backend
  template:
    metadata:
      labels:
        app: mmr
        tier: backend
    spec:
      containers:
      - name: yasp
        image: yasp/yasp:8c3dece
        args: [ "node", "mmr.js" ]
        imagePullPolicy: Always
      restartPolicy: Always