apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: parser
    tier: backend
    deployment: parser
  name: parser
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: parser
    tier: backend
  template:
    metadata:
      labels:
        app: parser
        tier: backend
    spec:
      volumes:
      - name: api-keys
        secret:
          secretName: api-keys
      containers:
      - name: yasp
        image: yasp/yasp:8c3dece
        args: [ "node", "parser.js" ]
        imagePullPolicy: Always
        volumeMounts:
        - name: api-keys
          readOnly: true
          mountPath: /etc/yasp-api-keys
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
