apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    app: postgres
    tier: backend
  template:
    metadata:
      labels:
        app: postgres
        deploymentconfig: postgres
        tier: backend
    spec:
      volumes:
      - name: postgres
        gcePersistentDisk:
          pdName: disk-postgres
          fsType: ext4
      - name: postgres-config
        secret:
          secretName: postgres-config
      containers:
      - name: postgres
        image: postgres:9
        args: [ "postgres", "-D", "/etc/postgresql" ]
        imagePullPolicy: Always
        ports:
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql
        - name: postgres-config
          mountPath: /etc/postgresql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
