apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: postgres
    tier: infra
  name: postgres
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: postgres
    tier: infra
  template:
    metadata:
      labels:
        app: postgres
        tier: infra
    spec:
      volumes:
      - name: postgres
        gcePersistentDisk:
          pdName: disk-postgres
          fsType: ext4
      - name: postgres-config
        secret:
          secretName: postgres-config
      containers:
      - name: postgres
        image: postgres:9
        command: ["postgres", "-u", "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql
        - name: postgres-config
          mountPath: /etc/postgresql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
