apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: postgres
    tier: infra
  name: postgres
spec:
  replicas: 1
  selector:
    app: postgres
    tier: infra
  template:
    metadata:
      labels:
        app: postgres
        deploymentconfig: postgres
        tier: infra
    spec:
      volumes:
      - name: postgres
        gcePersistentDisk:
          pdName: disk-postgres
          fsType: ext4
      - name: postgres-config
        secret:
          secretName: postgres-config
      containers:
      - name: postgres
        image: postgres:9
        args: [ "postgres", "-c" "config_file=/etc/postgresql/postgresql.conf", "-c" "hba_file=/etc/postgresql/hba.conf", "-c", "data_directory=/var/lib/postgresql/data"]
        imagePullPolicy: Always
        ports:
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
