apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    tier: infra
  name: postgres
spec:
  selector:
    app: postgres
    tier: backend
  ports:
  - port: 5432
    targetPort: postgres