apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: skill
    tier: backend
    deployment: skill
  name: skill
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: skill
    tier: backend
  template:
    metadata:
      labels:
        app: skill
        tier: backend
    spec:
      containers:
      - name: yasp
        image: yasp/yasp:latest
        args: [ "node", "skill.js" ]
        imagePullPolicy: Always
      restartPolicy: Always
