apiVersion: v1
kind: Service
metadata:
  labels:
    tier: frontend
  name: web
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: web
  selector:
    app: web
    tier: frontend
  type: NodePort
