apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: worker
    tier: backend
    deployment: worker
  name: worker
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: worker
    tier: backend
  template:
    metadata:
      labels:
        app: worker
        tier: backend
    spec:
      containers:
      - name: yasp
        image: yasp/yasp:latest
        args: [ "node", "worker.js" ]
        imagePullPolicy: Always
      restartPolicy: Always
